### ISSUE TITLE
why github action task in pining to exact git commit version/number instead of release tag?

### ISSUE THREAD

**Issue by SyedsImran** [OpenSourceHelpCommunity/Questions#217]
why is the GitHub action task is pining to the exact git commit version/number instead of the release tag?

We have a GitHub action task(APIsec Scan). 
We are trying to add this task through ```Get started with GitHub Actions``` search field. But after selecting this task we are getting a git commit version/number instead of the release tag v1.0.6 we specified while releasing the task.
![Githubaction1](https://user-images.githubusercontent.com/100760767/211078844-10ebcdf1-2fa2-4f4a-973b-630547f52963.png)
![githubaction2](https://user-images.githubusercontent.com/100760767/211079054-fadba08b-918c-4b88-97b9-58f5d04925bc.png)

```
  Trigger_APIsec_scan:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    steps:
       - name: APIsec scan
         uses: apisec-inc/apisec-run-scan@f748a240d69ca6cd7e9532fd0a47bec4ccd6a73c
         with:
          # The APIsec username with which the scans will be executed
          apisec-username: ${{ secrets.apisec_username }}
          # The Password of the APIsec user with which the scans will be executed
          apisec-password: ${{ secrets.apisec_password}}

```
While the same task added from the marketplace search field is working as expected.
![githubaction3](https://user-images.githubusercontent.com/100760767/211079386-2c7c41e1-647e-40eb-81c2-932f17a11f6c.png)

Is got something to do with this message we are getting when adding task from the Get started with GitHub Actions search field?

```
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
```
![githubaction5](https://user-images.githubusercontent.com/100760767/211079551-aa5b04e0-ad80-4b01-b39c-223343f85fb2.png)

So, why is the GitHub action task is pining to the exact git commit version/number instead of the release tag?
